onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - unrs-resolver
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: ^4.1.11
  vite-plus: ^0.3.0
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  workerd: true
